// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "features" section.

import React from 'react';
import FeaturesIconCards from "@/components/sections/features/FeaturesIconCards";

export default function FeaturesSection(): React.JSX.Element {
  return (
    <div id="features" data-section="features">
      <FeaturesIconCards
              tag="Why Teranga Jets"
              title="Why Contact Teranga Jets?"description="Experience swift, reliable operational coordination tailored for mission-critical flights across Africa."
              features={[
                { icon: "⚡", title: "Fast Response", description: "Permit processing and dispatch initiated instantly upon request." },
                { icon: "👤", title: "Dedicated Point of Contact", description: "Direct access to senior flight dispatchers managing your trip." },
                { icon: "🌍", title: "Local Expertise", description: "Deep relationships with African civil aviation authorities and ground crews." },
                { icon: "🛡️", title: "International Standards", description: "Strict safety adherence conforming to global aviation requirements." }
              ]}
              textAnimation="slide-up"
            />
    </div>
  );
}
