// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutTextSplit from '@/components/sections/about/AboutTextSplit';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutTextSplit
        title="Why Choose Teranga Jets"
        descriptions={["Built by Aviation Professionals. Trusted for Every Mission.","At Teranga Jets, we understand that every flight is unique.","Our mission is to deliver reliable, responsive and personalized operational support, allowing operators to focus on what matters most: safe and efficient flight operations.","From permits and ground handling to fuel coordination and crew services, we provide a single point of contact for seamless operations across Africa and beyond."]}
        textAnimation="slide-up"
      />
        </SectionErrorBoundary>
      </div>
  );
}
