// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutTextSplit from '@/components/sections/about/AboutTextSplit';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutTextSplit
        title="Why Choose Teranga Jets"
        descriptions={["Teranga Jets provides premium flight support based in Dakar, Senegal. We combine traditional African hospitality with rigorous international standards to ensure seamless operations across the continent.","Why Choose Teranga Jets: We offer 24/7 Operations, Fast Response, Local Expertise, Personalized Support, International Standards, and a Dedicated Operations Team.","Trust Teranga Jets as your strategic partner in African aviation. We handle the complexities so you can focus on your mission."]}
        textAnimation="slide-up"
      />
        </SectionErrorBoundary>
      </div>
  );
}
