// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="Ready to fly?"
          text="Get 24/7 Flight Support, Permits and Ground Handling with Teranga Jets. Experience the Teranga difference today."
          primaryButton={{
            text: "Contact Operations",
            href: "mailto:ops@terangajets.com",
          }}
          secondaryButton={{
            text: "WhatsApp Support",
            href: "https://wa.me/221000000000",
          }}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
