/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import ScrollReveal from "@/components/ui/ScrollReveal";
import TextAnimation from "@/components/ui/TextAnimation";
import Button from "@/components/ui/Button";

const primaryButton = {
  text: "Email ops@terangajets.com",
  href: "mailto:ops@terangajets.com"
};
const secondaryButton = {
  text: "WhatsApp +1 971 447 6728",
  href: "https://wa.me/19714476728"
};

const ContactInline = () => {
  return (
    <section aria-label="Contact section" className="py-20">
      <div className="w-content-width mx-auto">
        <ScrollReveal variant="fade-blur">
          <div className="flex flex-col items-center gap-8 md:gap-10 py-20 px-8 rounded card">
            <div className="flex flex-col items-center gap-2">
              <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
                <p>{"Ready for Your Next Mission?"}</p>
              </div>

              <TextAnimation
                text={"24/7 Flight Support, Permits,  and Operational Solutions Across Africa."}
                variant={"slide-up"}
                gradientText={true}
                tag="h2"
                className="md:max-w-8/10 text-5xl 2xl:text-6xl leading-[1.15] font-semibold text-center text-balance"
              />

              <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
                <Button text={primaryButton.text} href={primaryButton.href} variant="primary" className="hover:-translate-y-1 hover:shadow-lg transition-all duration-300" />
                <Button text={secondaryButton.text} href={secondaryButton.href} variant="secondary" animationDelay={0.1} className="hover:-translate-y-1 hover:shadow-lg transition-all duration-300" />
              </div>

              <p className="mt-4 text-sm text-accent text-center font-medium">
                Available 24/7 for Business Aviation, Cargo, Charter and MEDEVAC .
              </p>
            </div>
          </div>
        </ScrollReveal>
      </div>
    </section>
  );
};

export default function ContactSection() {
  return (
    <div data-webild-section="contact" data-section="contact" id="contact">
      <ContactInline />
    </div>
  );
}
