// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "coverage" section.

import React from 'react';
import FeaturesImageBento from '@/components/sections/features/FeaturesImageBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function CoverageSection(): React.JSX.Element {
  return (
    <div id="coverage" data-section="coverage">
        <SectionErrorBoundary name="coverage">
              <FeaturesImageBento
          tag="Our Operational Footprint"
          title="Serving Africa & International Operations"
          description="Strategic presence across major West African aviation hubs."
          items={[
            {
              title: "Senegal",
              description: "Dakar HQ",
              imageSrc: "http://img.b2bpic.net/free-photo/sky-april-18-2024_58702-17153.jpg",
            },
            {
              title: "Mauritania",
              description: "Operations",
              imageSrc: "http://img.b2bpic.net/free-photo/african-american-copilot-holding-lever-takeoff-with-airplane-flying-aircraft-with-dashboard-power-buttons-control-panel-command-radar-navigation-windscreen-compass-close-up_482257-50406.jpg",
            },
            {
              title: "Cape Verde",
              description: "Transit Support",
              imageSrc: "http://img.b2bpic.net/free-photo/asian-girl-walking-street-reading-tablet-drinking-coffee-outdoors_1258-193184.jpg",
            },
            {
              title: "Morocco",
              description: "Regional Hub",
              imageSrc: "http://img.b2bpic.net/free-photo/comic-style-airplane-illustration_23-2151813606.jpg",
            },
            {
              title: "Guinea",
              description: "Ground Handling",
              imageSrc: "http://img.b2bpic.net/free-photo/sports-plane-air-racing-render-3d-illustration_654080-72.jpg",
            },
            {
              title: "Ivory Coast",
              description: "Landing Support",
              imageSrc: "http://img.b2bpic.net/free-photo/black-white-portrait-working-woman-celebration-labour-day_23-2151296010.jpg",
            },
            {
              title: "Nigeria",
              description: "Key Market",
              imageSrc: "http://img.b2bpic.net/free-photo/supply-chain-representation-with-transportation-vehicles_52683-99738.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
