// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqTabbedAccordion from '@/components/sections/faq/FaqTabbedAccordion';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqTabbedAccordion
        tag="Common Queries"
        title="Operational Support FAQ"
        description="Clear answers to your aviation support questions."
        categories={[{"items":[{"question":"How fast can you secure permits?","answer":"Our dedicated dispatch team works in real-time with local authorities to expedite permits. We typically secure overflight permits within 24 hours and landing permits within 48 hours, depending on the country."},{"question":"Can you handle short-notice permit requests?","answer":"Yes, we can arrange short-notice permits for urgent flights, including medevac and diplomatic missions, leveraging our strong relationships with civil aviation authorities."}],"name":"Permits"},{"name":"Operations","items":[{"question":"Are you available 24/7?","answer":"Yes, our Operations Center is fully staffed 24/7/365 to handle urgent requests, monitor flights, and provide real-time updates."},{"question":"What ground handling services do you coordinate?","answer":"We provide comprehensive ground handling coordination, including ramp services, passenger and crew assistance, baggage handling, and aircraft servicing."}]},{"items":[{"question":"Do you offer crew support?","answer":"We provide premium crew assistance including VIP transport, hotel accommodations, and concierge services to ensure your crew is well-rested and prepared."},{"question":"Can you arrange VIP catering?","answer":"Yes, we coordinate high-quality VIP catering tailored to your specific dietary requirements and preferences, sourced from trusted local providers."}],"name":"Services"}]}
        textAnimation="slide-up"
      />
        </SectionErrorBoundary>
      </div>
  );
}
