/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import { useState } from "react";
import Button from "@/components/ui/Button";
import SelectorButton from "@/components/ui/SelectorButton";
import ScrollReveal from "@/components/ui/ScrollReveal";
import TextAnimation from "@/components/ui/TextAnimation";
import Transition from "@/components/ui/Transition";
import Accordion from "@/components/ui/Accordion";
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import { FileText, Settings, Briefcase } from "lucide-react";

const categories = [
  {
    name: "Permits",
    icon: FileText,
    items: [
      {
        question: "How fast can you secure overflight and landing permits?",
        answer: "Our dispatch team works directly with Civil Aviation Authorities across Africa. We typically secure overflight permits within 12-24 hours and landing permits within 24-48 hours, depending on the jurisdiction."
      },
      {
        question: "Can you handle short-notice or emergency permit requests?",
        answer: "Yes, we specialize in short-notice permits for urgent flights, including MEDEVAC, diplomatic, and humanitarian missions, leveraging our established relationships with local authorities."
      },
      {
        question: "Do you assist with PPR and airport slots?",
        answer: "Absolutely. We coordinate Prior Permission Required (PPR) and airport slots simultaneously with permit applications to ensure seamless arrival and departure scheduling."
      }
    ]
  },
  {
    name: "Operations",
    icon: Settings,
    items: [
      {
        question: "Are you available 24/7 for operational support?",
        answer: "Yes, our Operations Control Center (OCC) is fully staffed 24/7/365 to handle urgent requests, monitor active flights, and provide real-time updates to your dispatch team."
      },
      {
        question: "How do you handle fuel coordination?",
        answer: "We arrange reliable Jet A-1 fuel supply through our network of trusted providers, ensuring competitive pricing, timely delivery, and secure payment processing at all supported locations."
      },
      {
        question: "Do you provide on-site airport supervision?",
        answer: "Yes, our dedicated ground supervisors are present on the ramp to oversee all handling services, ensuring safety, efficiency, and adherence to your specific operational requirements."
      },
      {
        question: "Can you support cargo and charter operations?",
        answer: "We provide comprehensive support for both cargo and passenger charter operations, including specialized handling equipment coordination, loadmaster assistance, and customs clearance."
      }
    ]
  },
  {
    name: "Services",
    icon: Briefcase,
    items: [
      {
        question: "What ground handling services do you coordinate?",
        answer: "We oversee end-to-end ground handling, including ramp services, passenger and crew assistance, baggage handling, lavatory/water services, and GPU/ASU provision."
      },
      {
        question: "Do you offer crew support and logistics?",
        answer: "We arrange premium crew logistics, including secure VIP transport, vetted hotel accommodations, and visa-on-arrival assistance to ensure your crew is well-rested."
      },
      {
        question: "Can you arrange VIP catering?",
        answer: "Yes, we coordinate high-quality VIP catering tailored to specific dietary requirements, sourced from trusted local providers and premium hotels, delivered directly to the aircraft."
      }
    ]
  }
];

type FaqItem = {
  question: string;
  answer: string;
};

type FaqCategory = {
  name: string;
  items: FaqItem[];
};

interface FaqTabbedAccordionProps {
  tag: string;
  title: string;
  description: string;
  categories: FaqCategory[];
  textAnimation: "slide-up" | "fade-blur" | "fade";
  cta?: {
    name: string;
    role: string;
    buttonText: string;
    buttonHref: string;
  } & ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never });
}

const FaqInline = () => {
  const [activeCategory, setActiveCategory] = useState(categories[0]?.name || "");

  const currentItems = categories.find((c) => c.name === activeCategory)?.items || [];
  const accordionItems = currentItems.map((item) => ({ title: item.question, content: item.answer }));

  return (
    <section aria-label="FAQ section" className="py-20">
      <div className="w-content-width mx-auto">
        <div className="card rounded flex flex-col gap-6 md:gap-10 p-6 md:p-10">
          <div className="flex flex-col items-center gap-2">
            <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
              <p>{"Common Queries"}</p>
            </div>

            <TextAnimation
              text={"Operational Support FAQ"}
              variant={"slide-up"}
              gradientText={true}
              tag="h2"
              className="md:max-w-8/10 text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-center text-balance"
            />

            <TextAnimation
              text={"Find answers to the most common operational questions from flight departments, operators and dispatch teams."}
              variant={"slide-up"}
              gradientText={false}
              tag="p"
              className="md:max-w-7/10 text-lg md:text-xl leading-snug text-center text-balance"
            />

            <SelectorButton
              options={categories.map((c) => {
                const Icon = c.icon;
                return {
                  value: c.name,
                  label: (
                    <div className="flex items-center gap-2">
                      <Icon className="size-4" />
                      <span>{c.name}</span>
                    </div>
                  )
                };
              })}
              activeValue={activeCategory}
              onValueChange={setActiveCategory}
              className="mt-2 md:mt-3"
            />
          </div>

          <ScrollReveal variant="slide-up">
            <Transition key={activeCategory} whileInView={false} className="">
              <Accordion items={accordionItems} />
            </Transition>
          </ScrollReveal>

          <div className="w-full h-px bg-foreground/10 mt-4" />
          
          <div className="flex flex-col items-center gap-6 text-center pt-4">
            <h3 className="text-xl md:text-2xl font-semibold text-foreground">
              Didn't find your answer? Our Operations Team is available 24/7.
            </h3>
            <div className="flex flex-wrap justify-center gap-4">
              <Button 
                text="Contact Operations" 
                href="#contact" 
                variant="primary" 
              />
              <Button 
                text="WhatsApp Support" 
                href="https://wa.me/" 
                variant="secondary" 
              />
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default function FaqSection() {
  return (
    <div data-webild-section="faq" data-section="faq" id="faq">
      <FaqInline />
    </div>
  );
}
