// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroSplitVerticalMarqueeTall from '@/components/sections/hero/HeroSplitVerticalMarqueeTall';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroSplitVerticalMarqueeTall
        tag="African Hospitality. Global Aviation Excellence."
        title="Reliable Flight Support Across Africa"
        description="24/7 Flight Support, Permit Coordination, Ground Handling, Fuel Arrangements and Operational Solutions for Business Aviation."
        primaryButton={{"text":"Request Support Now","href":"#contact"}}
        secondaryButton={{"text":"Contact 24/7 Operations","href":"#contact"}}
        leftItems={[{"imageSrc":"https://images.unsplash.com/photo-1540962351504-03099e0a754b?q=80&w=1000&auto=format&fit=crop"},{"imageSrc":"https://images.unsplash.com/photo-1583416750470-965b2707b355?q=80&w=1000&auto=format&fit=crop"},{"imageSrc":"https://images.unsplash.com/photo-1517976487492-5750f3195933?q=80&w=1000&auto=format&fit=crop"},{"imageSrc":"https://images.unsplash.com/photo-1540962351504-03099e0a754b?q=80&w=1000&auto=format&fit=crop"},{"imageSrc":"https://images.unsplash.com/photo-1583416750470-965b2707b355?q=80&w=1000&auto=format&fit=crop"},{"imageSrc":"https://images.unsplash.com/photo-1517976487492-5750f3195933?q=80&w=1000&auto=format&fit=crop"}]}
        rightItems={[{"imageSrc":"https://images.unsplash.com/photo-1583416750470-965b2707b355?q=80&w=1000&auto=format&fit=crop"},{"imageSrc":"https://images.unsplash.com/photo-1517976487492-5750f3195933?q=80&w=1000&auto=format&fit=crop"},{"imageSrc":"https://images.unsplash.com/photo-1540962351504-03099e0a754b?q=80&w=1000&auto=format&fit=crop"},{"imageSrc":"https://images.unsplash.com/photo-1583416750470-965b2707b355?q=80&w=1000&auto=format&fit=crop"},{"imageSrc":"https://images.unsplash.com/photo-1517976487492-5750f3195933?q=80&w=1000&auto=format&fit=crop"},{"imageSrc":"https://images.unsplash.com/photo-1540962351504-03099e0a754b?q=80&w=1000&auto=format&fit=crop"}]}
        textAnimation="slide-up"
      />
        </SectionErrorBoundary>
      </div>
  );
}
