/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import { PlaneTakeoff, Activity, FileCheck, MapPin, Users, Headset } from "lucide-react";
import Button from "@/components/ui/Button";
import TextAnimation from "@/components/ui/TextAnimation";
import GridOrCarousel from "@/components/ui/GridOrCarousel";
import ScrollReveal from "@/components/ui/ScrollReveal";

const metrics = [
  {
    title: "24/7 Operations Center",
    value: "24/7",
    features: [
      { text: "Rapid Response", icon: PlaneTakeoff },
      { text: "Real-Time Mission Updates", icon: Activity }
    ]
  },
  {
    title: "Regional Expertise",
    features: [
      { text: "Permit Coordination", icon: FileCheck },
      { text: "Local Operational Knowledge", icon: MapPin }
    ],
    value: "Africa & International"
  },
  {
    title: "Operational Excellence",
    features: [
      { text: "Dedicated Operations Team", icon: Users },
      { text: "One Point of Contact", icon: Headset }
    ],
    value: "Mission Excellence"
  }
];

type Metric = {
  value: string;
  title: string;
  features: { text: string; icon: any }[];
};

const MetricsInline = () => (
  <section aria-label="Metrics section" className="py-20">
    <div className="flex flex-col gap-8 md:gap-10">
      <div className="flex flex-col items-center gap-2 w-content-width mx-auto">
        <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
          <p>{"Built by Aviation Professionals"}</p>
        </div>

        <TextAnimation
          text={"Operational Excellence"}
          variant={"fade"}
          gradientText={true}
          tag="h2"
          className="md:max-w-8/10 text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-center text-balance"
        />

        <TextAnimation
          text={"Proven capability and dedication to mission success."}
          variant={"fade"}
          gradientText={false}
          tag="p"
          className="md:max-w-7/10 text-lg md:text-xl leading-snug text-center text-balance"
        />

        {(undefined || undefined) && (
          <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
            {undefined && <Button text={undefined.text} href={undefined.href} variant="primary"/>}
            {undefined && <Button text={undefined.text} href={undefined.href} variant="secondary"animationDelay={0.1} />}
          </div>
        )}
      </div>

      <ScrollReveal variant="fade-blur">
        <GridOrCarousel>
          {metrics.map((metric) => (
            <div key={metric.value} className="flex flex-col justify-between gap-4 xl:gap-5 2xl:gap-6 p-6 xl:p-7 2xl:p-8 h-full card rounded">
              <div className="flex flex-col gap-0 min-w-0">
                <span className="text-8xl md:text-7xl font-semibold leading-none truncate">{metric.value}</span>
                <span className="text-xl truncate">{metric.title}</span>
              </div>

              <div className="flex flex-col gap-3 pt-5 border-t border-foreground/5">
                {metric.features.map((feature) => {
                  const Icon = feature.icon;
                  return (
                    <div key={feature.text} className="flex items-start gap-3">
                      <div className="flex items-center justify-center shrink-0 size-6 primary-button rounded">
                        <Icon className="size-3 text-primary-cta-text" strokeWidth={2} />
                      </div>
                      <span className="text-sm leading-snug">{feature.text}</span>
                    </div>
                  );
                })}
              </div>
            </div>
          ))}
        </GridOrCarousel>
      </ScrollReveal>
    </div>
  </section>
);

export default function MetricsSection() {
  return (
    <div data-webild-section="metrics" data-section="metrics" id="metrics">
      <MetricsInline />
    </div>
  );
}
