// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsFeatureCards from '@/components/sections/metrics/MetricsFeatureCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsFeatureCards
        tag="Performance Highlights"
        title="Operational Excellence"
        description="Proven capability and dedication to mission success."
        metrics={[{"title":"Dedicated Support","value":"24/7","features":["Real-time updates","Instant communication"]},{"title":"Regional Expertise","features":["Deep local knowledge","Permit efficiency"],"value":"Africa & International"},{"title":"Mission Success","features":["Operational stability","Proven consistency"],"value":"Focus"}]}
        textAnimation="fade"
      />
        </SectionErrorBoundary>
      </div>
  );
}
