/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import TextAnimation from "@/components/ui/TextAnimation";
import Button from "@/components/ui/Button";
import BorderGlow from "@/components/ui/BorderGlow";
import GridOrCarousel from "@/components/ui/GridOrCarousel";
import ScrollReveal from "@/components/ui/ScrollReveal";
import type { LucideIcon } from "lucide-react";
import { resolveIcon } from "@/utils/resolve-icon";

const features = [
  {
    description: "Seamless mission planning and execution.",
    title: "Flight Support",
    icon: "Plane"
  },
  {
    title: "Overflight & Landing Permits",
    description: "Expedited overflight and landing clearances.",
    icon: "FileText"
  },
  {
    title: "Ground Handling",
    icon: "Briefcase",
    description: "Comprehensive ground handling coordination."
  },
  {
    description: "Reliable refueling anywhere in Africa.",
    icon: "Droplets",
    title: "Fuel Coordination"
  },
  {
    description: "Expert routing and performance analysis.",
    title: "Flight Planning",
    icon: "Map"
  },
  {
    icon: "Users",
    title: "Crew Services",
    description: "Support for your pilots and passengers."
  },
  {
    icon: "Eye",
    title: "Airport Supervision",
    description: "On-site supervision for critical operations."
  },
  {
    icon: "PlaneTakeoff",
    description: "Charter coordination and management.",
    title: "Charter"
  },
  {
    title: "Cargo",
    icon: "Package",
    description: "Efficient logistics for heavy operations."
  },
  {
    icon: "HeartPulse",
    description: "Specialized support for medical flights.",
    title: "Medevac Support"
  }
];

type FeatureItem = {
  icon: string | LucideIcon;
  title: string;
  description: string;
};

interface FeaturesBorderGlowProps {
  tag: string;
  title: string;
  description: string;
  primaryButton?: { text: string; href: string };
  secondaryButton?: { text: string; href: string };
  features: FeatureItem[];
  textAnimation: "slide-up" | "fade-blur" | "fade";
}

const ServicesInline = () => {
  return (
    <section aria-label="Features border glow section" className="flex flex-col gap-8 md:gap-10 py-20">
      <div className="flex flex-col items-center gap-2 w-content-width mx-auto">
        <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
          <p>{"Our Expertise"}</p>
        </div>

        <TextAnimation
          text={"Global Aviation Services"}
          variant={"fade-blur"}
          gradientText={true}
          tag="h2"
          className="md:max-w-8/10 text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-center text-balance"
        />

        <TextAnimation
          text={"Comprehensive operational support tailored to the highest international standards."}
          variant={"fade-blur"}
          gradientText={false}
          tag="p"
          className="md:max-w-7/10 text-lg md:text-xl leading-snug text-center text-balance"
        />

        {(undefined || undefined) && (
          <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
            {undefined && <Button text={undefined.text} href={undefined.href} variant="primary" />}
            {undefined && <Button text={undefined.text} href={undefined.href} variant="secondary" animationDelay={0.1} />}
          </div>
        )}
      </div>

      <ScrollReveal variant="slide-up">
        <GridOrCarousel>
          {features.map((feature) => {
            const FeatureIcon = resolveIcon(feature.icon);
            return (
              <div key={feature.title} className="relative flex flex-col justify-between gap-4 xl:gap-5 2xl:gap-6 p-6 xl:p-7 2xl:p-8 mt-0.5 h-full min-h-60 md:min-h-70 2xl:min-h-80 card rounded">
                <div className="flex items-center justify-center size-12 md:size-14 2xl:size-16 primary-button rounded-full">
                  <FeatureIcon className="size-4 text-primary-cta-text" strokeWidth={1.5} />
                </div>
                <div className="flex flex-col gap-1">
                  <h3 className="text-2xl font-semibold leading-snug text-balance">{feature.title}</h3>
                  <p className="text-base leading-snug text-balance">{feature.description}</p>
                </div>
                <BorderGlow />
              </div>
            );
          })}
        </GridOrCarousel>
      </ScrollReveal>
    </section>
  );
};

export default function ServicesSection() {
  return (
    <div data-webild-section="services" data-section="services" id="services">
      <ServicesInline />
    </div>
  );
}
